CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);
----
CREATE TABLE "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_role
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_role FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_user FOREIGN KEY (user_id) REFERENCES "user" (id);
----
CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE category
(
    id          BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);
----
CREATE TABLE book
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255)                            NOT NULL,
    author         VARCHAR(255)                            NOT NULL,
    "release-year" INTEGER                                 NOT NULL,
    isbn           INTEGER                                 NOT NULL,
    price          DOUBLE PRECISION                        NOT NULL,
    description    VARCHAR(255)                            NOT NULL,
    category_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);
----
CREATE TABLE orders
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT,
    bill_code    VARCHAR(14)                              NOT NULL,
    full_name    VARCHAR(50)                              NOT NULL,
    email        VARCHAR(100)                             NOT NULL,
    phone_number VARCHAR(11)                              NOT NULL,
    address      VARCHAR(200)                             NOT NULL,
    note         VARCHAR(200),
    order_time   TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    status       VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USERID FOREIGN KEY (user_id) REFERENCES "user" (id);
----
CREATE TABLE order_detail
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id INTEGER,
    book_id  BIGINT,
    price    DOUBLE PRECISION                         NOT NULL,
    quantity INTEGER                                  NOT NULL,
    CONSTRAINT pk_order_detail PRIMARY KEY (id)
);

ALTER TABLE order_detail
    ADD CONSTRAINT FK_ORDER_DETAIL_ON_BOOKID FOREIGN KEY (book_id) REFERENCES book (id);

ALTER TABLE order_detail
    ADD CONSTRAINT FK_ORDER_DETAIL_ON_ORDERID FOREIGN KEY (order_id) REFERENCES orders (id);
----

